name: Check Changelog
on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled, unlabeled ]
    branches:
      - main
jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: ubuntu-22.04
    steps:
      - uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md